name : text_reader

services:
  db:
    image: mariadb:10.3
    healthcheck:
            test: [ "CMD", "healthcheck.sh", "--su-mysql", "--connect", "--innodb_initialized" ]
            start_period: 5s
            interval: 5s
            timeout: 5s
            retries: 5
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: text_reader
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - ./data:/var/lib/mysql

  backend:
    image: text_reader_backend
    build:
      context: .
      dockerfile: Dockerfile_backend
    ports:
      - "5000:5000"
    volumes:
      - ./:/app
    depends_on:
        db:
            condition: service_healthy

  text_reader:
    image: text_reader
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development